update deploy file with ruby version check

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -31,14 +31,16 @@ jobs:
            SECRET_KEY_BASE='$SECRET_KEY_BASE' \
            bash -s" << 'EOF'
 
-                        # Ensure RVM is accessible
-            if ! command -v rvm &> /dev/null
-            then
-              echo "RVM not found. Exiting..."
-              exit 1
-            else
+            # Source RVM from its default location
+            if [ -s "$HOME/.rvm/scripts/rvm" ]; then
               echo "RVM found. Sourcing RVM..."
               source "$HOME/.rvm/scripts/rvm"
+            elif [ -s "/etc/profile.d/rvm.sh" ]; then
+              echo "RVM system-wide installation found. Sourcing RVM..."
+              source /etc/profile.d/rvm.sh
+            else
+              echo "RVM not found. Exiting..."
+              exit 1
             fi
 
             # Ensure Ruby 3.2.0 is installed
@@ -73,6 +75,9 @@ jobs:
             else
               echo "Bundler is already installed."
             fi
+
+            # Print confirmation and exit
+            echo "RVM and Ruby environment set up correctly. Exiting gracefully."
 
             # Remove the old directory if it exists
             if [ -d "/var/www/html/scubadiving" ]; then
