try new updates on formating deploy yml file

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -54,27 +54,25 @@ jobs:
             # Change to the app directory
             cd /var/www/html/scubadiving
 
-            # Create .env file with the environment variables
-            echo "Creating .env file..."
-            cat <<EOT > /var/www/html/scubadiving/.env
-  SCUBADIVING_APP_DATABASE_NAME=${SCUBADIVING_APP_DATABASE_NAME}
-  SCUBADIVING_APP_DATABASE_USER=${SCUBADIVING_APP_DATABASE_USER}
-  SCUBADIVING_APP_DATABASE_PASSWORD=${SCUBADIVING_APP_DATABASE_PASSWORD}
-  SECRET_KEY_BASE=${SECRET_KEY_BASE}
-  EOT
-  
-  # Ensure the .env file is created successfully
-  if [ ! -f /var/www/html/scubadiving/.env ]; then
-  echo ".env file not created. Exiting."
-  exit 1
-  else
-  echo ".env file created successfully."
-  fi
-  
-  # Build and start Docker containers with the generated .env file
-  echo "Building Docker images and starting containers..."
-  sudo docker-compose down || true
-sudo docker-compose up -d --build || { echo "Error: Docker build failed"; exit 1; }
-  
-  echo "Deployment complete."
-  EOF
+            # Create .env file with the environment variables manually
+            echo "SCUBADIVING_APP_DATABASE_NAME=$SCUBADIVING_APP_DATABASE_NAME" >> /var/www/html/scubadiving/.env
+            echo "SCUBADIVING_APP_DATABASE_USER=$SCUBADIVING_APP_DATABASE_USER" >> /var/www/html/scubadiving/.env
+            echo "SCUBADIVING_APP_DATABASE_PASSWORD=$SCUBADIVING_APP_DATABASE_PASSWORD" >> /var/www/html/scubadiving/.env
+            echo "SECRET_KEY_BASE=$SECRET_KEY_BASE" >> /var/www/html/scubadiving/.env
+
+            # Ensure the .env file is created successfully
+            if [ ! -f /var/www/html/scubadiving/.env ]; then
+              echo ".env file not created. Exiting."
+              exit 1
+            else
+              echo ".env file created successfully."
+              cat /var/www/html/scubadiving/.env
+            fi
+
+            # Build and start Docker containers with the generated .env file
+            echo "Building Docker images and starting containers..."
+            sudo docker-compose down || true
+            sudo docker-compose up -d --build || { echo "Error: Docker build failed"; exit 1; }
+
+            echo "Deployment complete."
+          EOF
