update deploy file with ruby version check

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -30,11 +30,33 @@ jobs:
            SCUBADIVING_APP_DATABASE_PASSWORD='$SCUBADIVING_APP_DATABASE_PASSWORD' \
            SECRET_KEY_BASE='$SECRET_KEY_BASE' \
            bash -s" << 'EOF'
-          
-            # Load RVM and use Ruby 3.2.0
-            source "$HOME/.rvm/scripts/rvm"
+
+            # Install RVM and Ruby 3.2.0 if not installed
+            if ! command -v rvm &> /dev/null
+            then
+              echo "RVM not found. Installing RVM..."
+              sudo apt-get install -y curl gpg
+              curl -sSL https://rvm.io/mpapis.asc | gpg --import -
+              curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
+              curl -sSL https://get.rvm.io | bash -s stable
+              source "$HOME/.rvm/scripts/rvm"
+            else
+              echo "RVM is already installed."
+              source "$HOME/.rvm/scripts/rvm"
+            fi
+
+            # Install Ruby 3.2.0 if not installed
+            if ! rvm list rubies | grep "ruby-3.2.0" &> /dev/null
+            then
+              echo "Ruby 3.2.0 not found. Installing Ruby 3.2.0..."
+              rvm install 3.2.0
+            else
+              echo "Ruby 3.2.0 is already installed."
+            fi
+
+            # Set Ruby 3.2.0 as default
             rvm use 3.2.0 --default
-          
+
             # Check Ruby version
             echo "Using Ruby version:"
             ruby -v
