update deploy file with ruby version check

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -31,6 +31,22 @@ jobs:
            SECRET_KEY_BASE='$SECRET_KEY_BASE' \
            bash -s" << 'EOF'
           
+            # Load RVM and use Ruby 3.2.0
+            source "$HOME/.rvm/scripts/rvm"
+            rvm use 3.2.0 --default
+          
+            # Check Ruby version
+            echo "Using Ruby version:"
+            ruby -v
+
+            # Upgrade RubyGems
+            echo "Upgrading RubyGems..."
+            gem update --system 3.2.3
+
+            # Install bundler
+            echo "Installing Bundler..."
+            gem install bundler
+
             # Remove the old directory if it exists
             if [ -d "/var/www/html/scubadiving" ]; then
               echo "Removing old directory..."
@@ -43,20 +59,10 @@ jobs:
 
             # Change directory to the new clone
             cd /var/www/html/scubadiving || { echo "Directory not found"; exit 1; }
-          
-            # Ensure Ruby and Bundler are installed
-            echo "Installing Ruby and Bundler..."
-
-            # Install bundler if not installed
-            if ! gem spec bundler > /dev/null 2>&1; then
-              echo "Installing bundler..."
-              sudo gem install bundler -v 2.3.27 || { echo "Failed to install bundler"; exit 1; }
-            fi
 
             # Export the secret_key_base
             echo "Exporting SECRET_KEY_BASE..."
             export SECRET_KEY_BASE=$SECRET_KEY_BASE
-
 
             # Export the database credentials
             echo "Exporting database credentials..."
@@ -65,8 +71,7 @@ jobs:
             export SCUBADIVING_APP_DATABASE_PASSWORD=$SCUBADIVING_APP_DATABASE_PASSWORD
             export RAILS_ENV=production
 
-            # print all ENV variables
-
+            # Print all ENV variables
             echo "Checking all ENV variables..."
             env
 
@@ -76,20 +81,13 @@ jobs:
             # Define the path to the secure .env.production file
             SECURE_ENV_FILE="/var/app_credentials/scubadiving/.env.production"
 
-            # copy the environment variables to the app folder
+            # Copy the secure .env.production file to the app folder
             echo "Copying the secure .env.production file to the Rails app directory..."
             sudo cp $SECURE_ENV_FILE $APP_DIR || { echo "Failed to copy the .env.production file"; exit 1; }
 
-            # Copy the secure .env.production file to the Rails app directory
-
-            bundle config set force_ruby_platform true
-          
-            # move to the app directory
-            cd /var/www/html/scubadiving
-
+            # Install Ruby dependencies
             echo "Running bundle install..."
-            bundle install
-
+            bundle install --deployment --without development test || { echo "Bundle install failed"; exit 1; }
 
             # Run database migrations
             echo "Running database migrations..."
@@ -99,14 +97,7 @@ jobs:
             echo "Restarting Apache..."
             sudo systemctl restart apache2 || { echo "Failed to restart Apache"; exit 1; }
 
-            cd /var/www/html/scubadiving
-            export SCUBADIVING_APP_DATABASE_NAME=$SCUBADIVING_APP_DATABASE_NAME
-            export SCUBADIVING_APP_DATABASE_USER=$SCUBADIVING_APP_DATABASE_USER
-            export SCUBADIVING_APP_DATABASE_PASSWORD=$SCUBADIVING_APP_DATABASE_PASSWORD
-            export RAILS_ENV=production
-
-            echo "Checking all ENV variables..."
-            env
+            echo "Deployment complete."
           EOF
 
       - name: Cleanup
