add pre check before generation of certificates

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -50,29 +50,39 @@ jobs:
           sshpass -p $RASPBERRY_PI_PASSWORD ssh -o ServerAliveInterval=120 -o ServerAliveCountMax=100 -o StrictHostKeyChecking=no $RASPBERRY_PI_USER@$RASPBERRY_PI_IP <<EOF
             set -e
             echo "Deploying application..."
-
+          
             # Navigate to app directory
             cd /var/www/html/scubadiving
-
+          
             # Pull the latest image from Docker Hub
             echo "Pulling the latest Docker image..."
             docker pull elviajero34/scubadiving-app:latest
-
+          
             # Ensure Docker Compose is installed
             echo "Installing Docker Compose if not available..."
             if ! [ -x "$(command -v docker-compose)" ]; then
               sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-armv7" -o /usr/local/bin/docker-compose
               sudo chmod +x /usr/local/bin/docker-compose
             fi
-
+          
             # Stop old containers and start new ones
             echo "Restarting containers..."
             docker-compose down --remove-orphans
             docker-compose up -d --build
-            docker-compose run --rm certbot certonly --webroot --webroot-path=/var/lib/letsencrypt --email lucas.illiano@hotmail.com --agree-tos --no-eff-email -d scubadiving.nomadev.online
-
-
+          
+            # check certbot container
+            docker-compose run --rm certbot --version || { echo "Certbot not found! Exiting..."; exit 1; }
+          
+            # Generate SSL Certificate
+            echo "Generating SSL Certificate..."
+            docker-compose run --rm certbot certonly \
+              --webroot --webroot-path=/var/lib/letsencrypt \
+              --email lucas.illiano@hotmail.com \
+              --agree-tos --no-eff-email \
+              -d scubadiving.nomadev.online
+          
             # Run database migrations
             echo "Running database migrations..."
             docker-compose exec app bundle exec rake db:migrate
           EOF
+
